cmake_minimum_required(VERSION 4.3)
project(CSCI115)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Active labs
add_subdirectory("Lab 1")
add_subdirectory("Lab 2")

# Future labs (uncomment as you create the folders and their CMakeLists.txt files)
# add_subdirectory("Lab 3")
add_subdirectory("Lab 4")
# add_subdirectory("Lab 5")
# add_subdirectory("Lab 6")
# add_subdirectory("Lab 7")
# add_subdirectory("Lab 8")
# add_subdirectory("Lab 9")
# add_subdirectory("Lab 10")
# add_subdirectory("Lab 11")
# add_subdirectory("Lab 12")
# add_subdirectory("Lab 13")
# add_subdirectory("Lab 14")
# add_subdirectory("Lab 15")
# add_subdirectory("Lab 16")